In [1]:
import numpy as np

In [13]:
p1 = np.ones((4, 5), dtype = int)
p1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.randint (10, 50, 3)
df.ioc['a' %2 == 0] = -1

In [ ]:
p2 [1:21]

In [ ]:
df.iloc (['a' %3 ==0])
a

In [ ]:
p3 = np.reshape((2, 5), dtype = int)
p3

In [ ]:
df.loc ['2'] == 0

In [ ]:
b1 = np.array([1.5, 2, 3, 4, 5, 6, 7, 8, 9])
print(b1)

In [27]:
from numpy.random import seed
from numpy.random import rand
b2 = seed(1)
print(rand(3))
seed(1234)
print(rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[0.19151945 0.62210877 0.43772774]


In [ ]:
b2 = np.array([[1, 1], [2, 1], [3, -3]])
print(b2.transpose())

In [ ]:
b3 = b1.sum(b2)
print(b3)

In [ ]:
b3 = b1.dot(b2)
print(b3)